#!/bin/bash


HOMEFOLDER=${homefolder:-/home}
USERS=$(cat /etc/passwd | grep $HOMEFOLDER | cut -d":" -f1;)
TMPFILE=${tmpfile:-/tmp/plop}


top -b -n 1 > $TMPFILE
total=0;
 
case $1 in
	config)
		echo 'graph_title CPU usage, by user';
		echo 'graph_args --base 1000 -r --lower-limit 0';
		echo 'graph_category system';
		echo 'graph_info This graph shows CPU usage for every users matching the condition in configuration';
		echo 'graph_vlabel %'
		echo 'graph_period second'
		echo "graph_order $USERS total"

		for user in $USERS
		do
			echo "${user}.label $user"
			echo "${user}.info CPU usage for user $user"
		done
		echo "total.label total"
		echo "total.info CPU usage for every users"
		exit 0;;
esac


for user in $USERS
do
     
    echo ${user}.type GAUGE
    cpu=`cat $TMPFILE | grep $user | awk 'BEGIN{sum =0} {sum +=$9;  } END {print sum;}'`;
    echo ${user}.value $cpu
 	total=$($total + $cpu);
done
echo 'total.type GAUGE'
echo "total.value $total"
rm -rf $TMPFILE